export const GET_POSTINGS = 'GET_POSTINGS';
export const GET_POSTING = 'GET_POSTING';
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const SHOW_COMMON_PROGRESS_BAR = 'SHOW_COMMON_PROGRESS_BAR';
export const HIDE_COMMON_PROGRESS_BAR = 'HIDE_COMMON_PROGRESS_BAR';
export const SET_FILTER = 'SET_FILTER';